/**
 * Layer 2 of country resolution: the offline registry table.
 *
 * Used when the platform did not already tell us the country (see
 * ./headers.ts). The data in ./data.ts is a snapshot of the regional internet
 * registries' delegation records, regenerated by scripts/build-geo-table.py.
 *
 * The encoded strings are decoded into typed arrays on first use rather than
 * at import time, so a request that never reaches this layer - anything on
 * Vercel, Cloudflare or another platform with a geo header - pays nothing for
 * the table beyond the bytes sitting in the bundle.
 */

import {
  COUNTRIES,
  IPV4_COUNT,
  IPV4_RANGES,
  IPV6_COUNT,
  IPV6_RANGES,
} from "./data";
import { isPrivate, parseIp } from "./ip";

interface RangeTable {
  /** First address of each range, ascending. */
  starts: Uint32Array;
  /** One past the last address of each range. */
  ends: Uint32Array;
  /** Index into COUNTRIES, two characters per entry. */
  countries: Uint16Array;
}

const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";

/** Character code -> its 6-bit value, for a branch-free decode. */
const VALUES = (() => {
  const table = new Uint8Array(128);
  for (let i = 0; i < ALPHABET.length; i += 1) table[ALPHABET.charCodeAt(i)] = i;
  return table;
})();

/**
 * Expands the encoding described in data.ts: three integers per range, each
 * written little-endian in base 32 with bit 6 marking "another character
 * follows". Arithmetic rather than shifts, because a 32-bit range start would
 * come back negative from `<<`.
 */
function decode(encoded: string, count: number): RangeTable {
  const starts = new Uint32Array(count);
  const ends = new Uint32Array(count);
  const countries = new Uint16Array(count);

  let value = 0;
  let scale = 1;
  let field = 0;
  let row = 0;
  let position = 0;

  for (let i = 0; i < encoded.length; i += 1) {
    const digit = VALUES[encoded.charCodeAt(i)];
    value += (digit & 31) * scale;

    if (digit & 32) {
      scale *= 32;
      continue;
    }

    if (field === 0) {
      position += value; // gap since the previous range ended
      starts[row] = position;
    } else if (field === 1) {
      position += value; // range length
      ends[row] = position;
    } else {
      countries[row] = value;
      row += 1;
    }

    field = (field + 1) % 3;
    value = 0;
    scale = 1;
  }

  return { starts, ends, countries };
}

let ipv4: RangeTable | null = null;
let ipv6: RangeTable | null = null;

function ipv4Table(): RangeTable {
  if (!ipv4) ipv4 = decode(IPV4_RANGES, IPV4_COUNT);
  return ipv4;
}

function ipv6Table(): RangeTable {
  if (!ipv6) ipv6 = decode(IPV6_RANGES, IPV6_COUNT);
  return ipv6;
}

/** Rightmost range starting at or before `address`, or `null` if outside it. */
function search(table: RangeTable, address: number): string | null {
  let low = 0;
  let high = table.starts.length - 1;
  let found = -1;

  while (low <= high) {
    const middle = (low + high) >>> 1;
    if (table.starts[middle] <= address) {
      found = middle;
      low = middle + 1;
    } else {
      high = middle - 1;
    }
  }

  // Ranges do not cover the whole address space - the gaps are unallocated.
  if (found === -1 || address >= table.ends[found]) return null;

  const index = table.countries[found] * 2;
  return COUNTRIES.slice(index, index + 2) || null;
}

/**
 * Resolves an IP to an ISO 3166-1 alpha-2 country code, or `null` when the
 * address belongs to no country - private and loopback ranges, unallocated
 * space, or anything unparseable.
 */
export function countryFromIp(ip: string): string | null {
  const parsed = parseIp(ip);
  if (!parsed || isPrivate(parsed)) return null;

  return parsed.version === 4
    ? search(ipv4Table(), parsed.value)
    : search(ipv6Table(), parsed.key);
}
